name: Deploy HTML to EC2 with NGINX

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload HTML to EC2
      env:
        EC2_USER: ec2-user
        EC2_IP: 34.205.17.226  # Cambia por tu IP pública
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$SSH_KEY" > WebClave.pem
        chmod 600 WebClave.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts
        # Copiar archivos al nuevo directorio
        scp -i WebClave.pem index.html $EC2_USER@$EC2_IP:/home/ec2-user/downloads/EC2WorkFlows/
        rm WebClave.pem

    - name: Reload NGINX
      env:
        EC2_USER: ec2-user
        EC2_IP: 34.205.17.226  # Cambia por tu IP pública
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$SSH_KEY" > WebClave.pem
        chmod 600 WebClave.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts
        ssh -i WebClave.pem $EC2_USER@$EC2_IP "sudo systemctl restart nginx"
        rm WebClave.pem
