name: Deploy to EC2

on:
  push:
    branches:
      - main  # O la rama de tu preferencia

jobs:
  deploy:
    runs-on: ubuntu-latest  # El runner de GitHub para ejecutar la acción

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Utilizamos el secreto de la clave privada

    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./ ec2-user@54.161.138.112:/var/www/html/
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # Esta es la clave privada cargada como secreto

    - name: Restart web server (optional)
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@54.161.138.112 "sudo systemctl restart httpd"
