name: Deploy to EC2

on:
  push:
    branches:
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las EC2
      - name: Set up SSH key and AWS region
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Agregar las direcciones IP de las instancias EC2
          ssh-keyscan -H 3.86.86.51 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.166.247.208 >> ~/.ssh/known_hosts
          ssh-keyscan -H 52.70.93.208 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.237.220.45 >> ~/.ssh/known_hosts  # IP para QA

      # Paso 3: Desplegar a QA cuando se hace un push en la rama qa
      - name: Deploy to QA (if on qa branch)
        if: github.ref == 'refs/heads/qa'
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.237.220.45 << 'EOF'
            if [ ! -d "/home/ec2-user/EC2WorkFlows" ]; then
              git clone https://github.com/Danyss09/EC2WorkFlows.git /home/ec2-user/EC2WorkFlows
            fi
            cd /home/ec2-user/EC2WorkFlows
            git pull origin qa  # Actualizar los archivos del repositorio desde la rama qa
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx

            # Paso adicional para realizar un push si hubo cambios
            git add index.html
            git commit -m "Actualización de index.html desde EC2"
            git push origin qa  # Realizar push a la rama qa
          EOF


      # Paso 4: Desplegar a Producción cuando se hace un pull request en la rama main
      - name: Deploy to Prod (if on main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.86.86.51 << 'EOF'
            if [ ! -d "/home/ec2-user/EC2WorkFlows" ]; then
              git clone https://github.com/Danyss09/EC2WorkFlows.git /home/ec2-user/EC2WorkFlows
            fi
            cd /home/ec2-user/EC2WorkFlows
            git pull origin main  # Actualizar los archivos del repositorio desde la rama main
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF
          
          ssh -o StrictHostKeyChecking=no ec2-user@54.166.247.208 << 'EOF'
            if [ ! -d "/home/ec2-user/EC2WorkFlows" ]; then
              git clone https://github.com/Danyss09/EC2WorkFlows.git /home/ec2-user/EC2WorkFlows
            fi
            cd /home/ec2-user/EC2WorkFlows
            git pull origin main  # Actualizar los archivos del repositorio desde la rama main
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF

          ssh -o StrictHostKeyChecking=no ec2-user@52.70.93.208 << 'EOF'
            if [ ! -d "/home/ec2-user/EC2WorkFlows" ]; then
              git clone https://github.com/Danyss09/EC2WorkFlows.git /home/ec2-user/EC2WorkFlows
            fi
            cd /home/ec2-user/EC2WorkFlows
            git pull origin main  # Actualizar los archivos del repositorio desde la rama main
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF
          
        
