name: Deploy to EC2 - Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con la EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.86.86.51 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.166.247.208 >> ~/.ssh/known_hosts
          ssh-keyscan -H 52.70.93.208 >> ~/.ssh/known_hosts

      # Paso 3: Desplegar a Producción cuando se hace un push en la rama main
      - name: Deploy to Prod Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.86.86.51 << 'EOF'
            if [ ! -d "/home/ec2-user/EC2WorkFlows" ]; then
              git clone https://github.com/Danyss09/EC2WorkFlows.git /home/ec2-user/EC2WorkFlows
            fi
            cd /home/ec2-user/EC2WorkFlows
            git pull origin main  # Actualizar los archivos del repositorio desde la rama main
            sudo cp index.html /var/www/html/
            sudo systemctl restart nginx
          EOF

      - name: Deploy to Prod Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.166.247.208 << 'EOF'
            if [ ! -d "/home/ec2-user/EC2WorkFlows" ]; then
              git clone https://github.com/Danyss09/EC2WorkFlows.git /home/ec2-user/EC2WorkFlows
            fi
            cd /home/ec2-user/EC2WorkFlows
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo systemctl restart nginx
          EOF

      - name: Deploy to Prod Instance 3
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.70.93.208 << 'EOF'
            if [ ! -d "/home/ec2-user/EC2WorkFlows" ]; then
              git clone https://github.com/Danyss09/EC2WorkFlows.git /home/ec2-user/EC2WorkFlows
            fi
            cd /home/ec2-user/EC2WorkFlows
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo systemctl restart nginx
          EOF
