name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.234.71.238 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.221.78.57 >> ~/.ssh/known_hosts

      # Paso 3: Desplegar los archivos a la primera instancia EC2
      - name: Deploy to EC2 Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.234.71.238 << 'EOF'
            cd /home/ec2-user/EC2WorkFlows
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF

      # Paso 4: Desplegar los archivos a la segunda instancia EC2
      - name: Deploy to EC2 Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.221.78.57 << 'EOF'
            cd /home/ec2-user/EC2WorkFlows
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF
