name: Deploy to EC2 - QA

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con la EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.237.220.45 >> ~/.ssh/known_hosts  # IP para QA

      # Paso 3: Desplegar a QA cuando se hace un push en la rama qa
      - name: Deploy to QA
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.237.220.45 << 'EOF'
            if [ ! -d "/home/ec2-user/EC2WorkFlows" ]; then
              git clone https://github.com/Danyss09/EC2WorkFlows.git /home/ec2-user/EC2WorkFlows
            fi
            cd /home/ec2-user/EC2WorkFlows
            git pull origin qa  # Actualizar los archivos del repositorio desde la rama qa

            # Copiar index.html al directorio de Nginx y reiniciar el servicio
            sudo cp index.html /var/www/html/
            sudo systemctl restart nginx
          EOF
